### ISSUE TITLE
Not seeing color highlight in demo

### ISSUE THREAD

**Issue by boltex** [Trinovantes/rst-compiler#3]
Hi Stephen! 

Thank you for this great project! 😄 

I'm a bit of a newbie with rst, and I'm trying to understand how to use your converter. _(sorry in advance for this possibly silly question)_

I've tried the live demo at https://trinovantes.github.io/rst-compiler/ you have setup and when I try the code snippet feature, it does not get colorized as I would have expected... Is it intended?

Screenshot below with the sample below inserted in the demo on the left.

```
.. code:: python

   def my_function():
       "just a test"
       print(8/2)
```
 

![image](https://github.com/user-attachments/assets/a5f63c8f-39db-44c3-afbd-b5d15ff35be6)

**Comment by Trinovantes** [comment]
By default, I simply output the code in `<pre>` tags (when using the html generator)

If you want syntax highlighting, you'll need to provide `shiki` in `RstGeneratorOptions`:

```ts
import { getHighlighter } from 'shiki'

RstToHtmlCompiler.compile(rst, {}, {
    shiki: {
        defaultLanguage: 'python',
        theme: 'min-dark',
        transformers: [],
        highlighter: await getHighlighter({
            langs: ['py', 'js', 'cpp'],
            themes: ['min-dark'],
        }),
    },
})
```

**Comment by Trinovantes** [comment]
I've just updated the demo to have syntax highlighting

**Comment by boltex** [comment]
Wow! Thanks!
