### ISSUE TITLE
Error: Duplicate simpleName for hyperlink and section id

### ISSUE THREAD

**Issue by TheMentalist-w** [Trinovantes/rst-compiler#4]
In my rst file, there is a section "Documentation" and a hyperlink in the paragraph "documentation_". The file can't be parsed and returns error:

```
Uncaught (in promise) Error: Duplicate simpleName:"documentation"
    registerNodeForwardTarget SimpleNameResolver.ts:160
    registerHyperlinkTargets SimpleNameResolver.ts:415
    registerHyperlinks SimpleNameResolver.ts:497
    SimpleNameResolver SimpleNameResolver.ts:56
    createParserOutput RstCompiler.ts:164
    get parserOutput RstParserState.ts:73
    parse RstCompiler.ts:106
    compile RstCompiler.ts:176
    setup PackageDescription.vue:95
    callWithErrorHandling runtime-core.esm-bundler.js:195
SimpleNameResolver.ts:160:18
```
Is there a way to parse this file correctly without prior knowledge of whether or not this situation may occur? I cannot modify rst files since they are a response from API and are only displayed for the user on the page.
I'm currently modifying the file before parsing by adding 'a{line_number}' to the section titles. That way after parsing the id attached to section tags has a different id than the hyperlink id. However, after parsing I need to go through the html and remove 'a{line_number}' from the actual text in titles displayed for the user. It's troublesome and inefficient

**Comment by Trinovantes** [comment]
I need a minimum reproduction example

**Comment by TheMentalist-w** [comment]
Yes, sorry for that. As an example, I used this file https://github.com/pypa/wheel/blob/main/README.rst
and I basically use only this command
`const html = new RstToHtmlCompiler().compile(rst)`
without the Documentation section, the file is parsed correctly and I couldn't find any solution that wouldn't throw the above error without my own workaround.
